Implement env variables for dev/prod and move fetch logic out of component for better structure

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -3,12 +3,17 @@ FROM node:20-alpine
 
 WORKDIR /app
 
-# Install dependencies
-COPY package*.json ./
-RUN npm install
-
 # Copy the rest of the app
 COPY . .
+
+# Exit if .env.development file is missing
+RUN if [ ! -f /app/.env.development ]; then \
+      echo "ERROR: .env.development file is missing in /app"; \
+      exit 1; \
+    fi
+
+# Install dependencies
+RUN npm install
 
 # Expose port Vite runs on
 EXPOSE 5173
